server:
  port: 8082

# Redis 配置
spring:
  redis:
    # 数据库编号 0-15
    database: 4
    # Redis服务器连接IP
    host: 101.37.159.158
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ""
    # 连接超时时间（毫秒）
    timeout: 1000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 0
